# Default values for my-charts.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: techcloudifyme/my-app-1
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v1"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""


service:
  type: NodePort
  port: 80
  nodePort: 30081  

nodeSelector: {}

tolerations: []

affinity: {}
