# Default values for my-charts.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: techcloudifyme/my-app-2
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v2"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""


service:
  type: NodePort
  port: 80
  nodePort: 30082  

nodeSelector: {}

tolerations: []

affinity: {}
